import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bojan
 */
public class Password extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form ForgetPassword
     */
    public Password() {
        initComponents();
        conn=Data.javaconnect.ConnecrDb();// Preusmerenje na klasu za konekciju na bazu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_pass = new javax.swing.JPanel();
        Label_email_forget = new javax.swing.JLabel();
        txt_email_forget = new javax.swing.JTextField();
        Button_Send_forgetpassword = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        Label_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Obnova Lozinke");
        setName("ForgetPassword"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel_pass.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_pass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obnova Lozinke", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel_pass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        Label_email_forget.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Label_email_forget.setText("Unesite Vaš Email");

        txt_email_forget.setToolTipText("Unesite Vašu Email adresu kako bi ste uspešno poslali zahtev za obnovu Vaše lozinke.");

        Button_Send_forgetpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Button_Send_forgetpassword.setText("Pošalji Zahtev");
        Button_Send_forgetpassword.setToolTipText("Pošaljite zahtev za obnovu lozinke");
        Button_Send_forgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Send_forgetpasswordActionPerformed(evt);
            }
        });
        Button_Send_forgetpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Button_Send_forgetpasswordKeyPressed(evt);
            }
        });

        jButtonLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonLogin.setText("Povratak na Ulaz ");
        jButtonLogin.setToolTipText("Vraćate se u Ulaz na Sistem");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jButtonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonLoginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_passLayout = new javax.swing.GroupLayout(jPanel_pass);
        jPanel_pass.setLayout(jPanel_passLayout);
        jPanel_passLayout.setHorizontalGroup(
            jPanel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_passLayout.createSequentialGroup()
                .addComponent(Label_email_forget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Send_forgetpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_email_forget)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_passLayout.setVerticalGroup(
            jPanel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_passLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_email_forget)
                    .addComponent(txt_email_forget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_Send_forgetpassword)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        Label_email_forget.getAccessibleContext().setAccessibleName("Insert_Your_Email");
        txt_email_forget.getAccessibleContext().setAccessibleName("Forget_Password");
        Button_Send_forgetpassword.getAccessibleContext().setAccessibleName("Send_Forget_Password");

        Label_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafika/Users-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Label_logo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(590, 267));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void Button_Send_forgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Send_forgetpasswordActionPerformed
         // zaboravljena lozinka
        zaboravljenaLozinka();
        
    }//GEN-LAST:event_Button_Send_forgetpasswordActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // Nazad na login
        nazadLogin();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLoginKeyPressed
        // Nazad na login ako je pritisnut enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            // Nazad na login
            nazadLogin();
        }
    }//GEN-LAST:event_jButtonLoginKeyPressed

    private void Button_Send_forgetpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Button_Send_forgetpasswordKeyPressed
        // zaboravljena lozinka ako je pritisnuto dugme
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            // zaboravljena lozinka
            zaboravljenaLozinka();
        }
    }//GEN-LAST:event_Button_Send_forgetpasswordKeyPressed
    //povratak na login
    public void nazadLogin(){
        JOptionPane.showMessageDialog(null, "Vratićate se u Ulaz na Sistem!");
        //otvaranje prozora Login
        dispose();//zatvaranje prozora
        new Login().setVisible(true);
    }
    //metod za zaboravljenu lozinku
    public void zaboravljenaLozinka(){
        //sql upit za proveru meil adrese
        String sql ="select Email from korisnici where Email=?";
        
        try{
        pst=conn.prepareStatement(sql);
        pst.setString(1,txt_email_forget.getText());
        
        rs=pst.executeQuery();
        
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Uneta Email adresa se podudara Vi ste Uspešno prosledili zahtev za obnovu lozinke Možete očekivati da Vas Administrator kontaktira kako bi ste potvrdili zahtev za obnovu zaboravljene lozinke!");
                // unos zahteva za obnovu lozinke u bazu
                try{
                    
                    String sql1="Insert into obnova_lozinke(Email) values (?)";
                    pst=conn.prepareStatement(sql1);
                    pst.setString(1,txt_email_forget.getText());
                    pst.execute();   
                }
                catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Vaši podaci poslati kao zahtev za obnovu lozinke nije sačuvan i poslat Administratoru, Pokušajte opet!","Unos Podatkaka",JOptionPane.OK_OPTION);               
                }
                rs.close();
                pst.close();
            //otvaranje prozora za login ukoliko je meil poslat
                dispose();//zatvaranje prozora
                new Login().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Uneta Email adresa se ne podudara Molimo Vas upišite odgovarajuću Email adresu!");
            }
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        } finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e){
                }
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Send_forgetpassword;
    private javax.swing.JLabel Label_email_forget;
    private javax.swing.JLabel Label_logo;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JPanel jPanel_pass;
    private javax.swing.JTextField txt_email_forget;
    // End of variables declaration//GEN-END:variables
}
